name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ main ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  